app.menus:
  - title: User
    name: User
    path: /user
  - title: Login
    name: Login
    path: /login   
  - title: Logout
    name: Logout
    path: /logout         
  - title: Socket-Chart
    name: Socket-Chart
    path: /chart
jdbc:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1
hibernate:
   show_sql: true
   packagesToScan: dev.fringe.entity
   hbm2ddl:
      auto: create
spring:
   mustache:
      prefix: classpath:/views/
      suffix: .html
      