app.menus:
  - title: User
    name: User
    path: /user
  - title: Login
    name: Login
    path: /login   
  - title: Logout
    name: Logout
    path: /logout         
  - title: Socket-Chart
    name: Socket-Chart
    path: /chart
  - title: Category
    name: Category
    path: /category    
jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    password: moby3776
    username: root
hibernate:
   show_sql: true
   dialect: org.hibernate.dialect.MySQL5Dialect
   packagesToScan: dev.fringe.entity
   hbm2ddl:
      auto: create
spring:
   mustache:
      prefix: classpath:/views/
      suffix: .html
      